---
title: "Modeling"
format: html
editor: visual
---

```{r, include=FALSE}
#Clearing the working environment
rm(list=ls())
```

```{r}
#Loading packages
library("tidyverse")
library("tidymodels")
library("caret")
library("yardstick")
library("baguette")
```

Loading in the cleaned data

```{r}
#Reading in the data
diabetes_data <- read.csv("diabetes_binary_health_indicators_BRFSS2015.csv")
```

```{r}
#Selecting response and 3 chosen explanatory variables
#Converting categorical variables from numeric variables to factor variables
diabetes_select <- diabetes_data |>
  rename("diabetes_resp" = Diabetes_binary) |>
  rename("bmi" = BMI) |>
  rename("physical_activity" = PhysActivity) |>
  rename("age" = Age) |>
  mutate(diabetes_resp = factor(diabetes_resp, levels = c(0, 1), labels = c("No diabetes", "Prediabetes or diabetes"))) |>
  mutate(physical_activity = factor(physical_activity, levels = c(0, 1), labels =c("No physical activity", "Physical activity"))) |>
  mutate(age = factor(age, levels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13), labels = c("Age 18-24", "Age 25-29", "Age 30-34", "Age 35-39", "Age 40-44", "Age 45-49", "Age 50-54", "Age 55-59", "Age 60-64", "Age 65-69", "Age 70-74", "Age 75-79", "Age 80 or older"))) |>
  mutate(HvyAlcoholConsump = as.factor(HvyAlcoholConsump)) |>
  mutate(AnyHealthcare = as.factor(AnyHealthcare))
```

## Introduction

## Modeling

### Splitting Data into Training and Testing

```{r}
set.seed(1234)

diabetes_split <- initial_split(diabetes_select, prop = 0.70) #specifying a 70/30 split
diabetes_train <- training(diabetes_split) #splitting training data
diabetes_test <- testing(diabetes_split) #splitting testing data

diabetes_folds <- vfold_cv(diabetes_train, 5) #creating 10 fold CV of the training data
```

### Logistic Regression Models

```{r}
#Creating the spec for logistic models
LR_spec <- logistic_reg() |>
  set_engine("glm")
```

```{r}
#Creating the first logistic model using 
#Resting Blood Pressure, Sex, and Cholesterol as predictors
LR1_rec <- recipe(diabetes_resp ~ physical_activity + bmi + age + HvyAlcoholConsump + AnyHealthcare, data = diabetes_train) |>
  step_normalize(bmi) |>
  step_dummy(physical_activity, age, HvyAlcoholConsump, AnyHealthcare)

LR1_wkf <- workflow() |>
  add_recipe(LR1_rec) |>
  add_model(LR_spec)

LR1_fit <- LR1_wkf |>
  fit_resamples(diabetes_folds, metrics = metric_set(mn_log_loss))
```

```{r}
#Creating the first logistic model using 
#Max heart rate, Age, and Sex as predictors
LR2_rec <- recipe(diabetes_resp ~ bmi + physical_activity + HvyAlcoholConsump + AnyHealthcare, data = diabetes_train) |>
  step_dummy(physical_activity, HvyAlcoholConsump, AnyHealthcare)

LR2_wkf <- workflow() |>
  add_recipe(LR2_rec) |>
  add_model(LR_spec)

LR2_fit <- LR2_wkf |>
  fit_resamples(diabetes_folds, metrics = metric_set(mn_log_loss))
```

```{r}
#Creating the first logistic model using 
#Max heart rate, Age, and Sex as predictors
LR3_rec <- recipe(diabetes_resp ~ bmi + physical_activity + age, data = diabetes_train) |>
  step_normalize(bmi) |>
  step_dummy(physical_activity, age)

LR3_wkf <- workflow() |>
  add_recipe(LR3_rec) |>
  add_model(LR_spec)

LR3_fit <- LR3_wkf |>
  fit_resamples(diabetes_folds, metrics = metric_set(mn_log_loss))
```

```{r}
rbind(LR1_fit |> collect_metrics(),
      LR2_fit |> collect_metrics(),
      LR3_fit |> collect_metrics()) |>
  mutate(Model = c("Model1", "Model2", "Model3")) |>
  select(Model, everything())
```

### Classification Tree

```{r}
tree_rec <- recipe(diabetes_resp ~ ., data = diabetes_train) |>
  #update_role(name, new_role = "ID") |>
  #step_log(km_driven) |>
  #step_rm(ex_showroom_price) |>
  step_dummy(physical_activity, age, HvyAlcoholConsump, AnyHealthcare) |>
  step_normalize(bmi, -all_outcomes())

tree_mod <- decision_tree(tree_depth = tune(), min_n = 200, cost_complexity = tune()) |>
  set_engine("rpart") |>
  set_mode("classification")

tree_wkf <- workflow() |>
  add_recipe(tree_rec) |>
  add_model(tree_mod)

tree_grid <- grid_regular(cost_complexity(),
                          tree_depth(),
                          levels = c(10, 5))

tree_fits <- tree_wkf |> 
  tune_grid(resamples = diabetes_folds,
            grid = tree_grid, 
            metrics = metric_set(mn_log_loss))

tree_fits |> collect_metrics()
```

### Random Forest

```{r}
rf_spec <- rand_forest(mtry = tune()) |>
  set_engine("ranger") |>
  set_mode("classification")

rf_wkf <- workflow() |>
  add_recipe(LR1_rec) |>
  add_model(rf_spec)

rf_fit <- rf_wkf |>
  tune_grid(resamples = diabetes_folds,
            grid = 7,
            metrics = metric_set(accuracy, mn_log_loss))
```


```{r}
rf_fit |>
  collect_metrics() |>
  filter(.metric == "mn_log_loss") |>
  arrange(mean)
```

```{r}
rf_fit |> 
  collect_metrics() |>
  filter(.metric == "mn_log_loss")
```

```{r}
rf_best_params <- select_best(rf_fit, metric = "mn_log_loss")
rf_best_params
```

```{r}
rf_final_wkf <- rf_wkf |>
 finalize_workflow(rf_best_params)
rf_final_fit <- rf_final_wkf |>
 last_fit(diabetes_split, metrics = metric_set(mn_log_loss))
```

```{r}
rf_final_fit |> collect_metrics()
```


### Final Model Selection
